### ISSUE TITLE
is<T> for non-valid T is a compiler error

### ISSUE THREAD

**Issue by Rapptz** [Rapptz/jsonpp#10]
Essentially the title.

Rather than returning `false` like it should do, it just fails to compile instead making it a hassle for generic programming. This also applies to `as<T>()` though I'm not sure what the course of action should be for that.

Example:

```cpp
#include <jsonpp.hpp>

struct pod {};

int main() {
    json::value x;
    return x.is<pod>();
}
```

Expected: `return 0;` equivalent.
Actual: Compiler error.

**Comment by jplatte** [comment]
Since this is fixed, the [reference to it in the API documentation](http://rapptz.github.io/jsonpp/doc/api.html#_GCPPKN4json5value2isI1TEEv) should probably be removed, right?
