### ISSUE TITLE
Support for VS2013

### ISSUE THREAD

**Issue by Rapptz** [Rapptz/jsonpp#13]
A couple of changes required (thanks to Cicada of Lounge\<C++\>):

- [x] No using `inline namespace`. 
    - Solution: Take them out completely (unfortunately)
- [x] No using `noexcept`. 
    - Solution: Hide it behind a macro.
- [x] Removing using alternative token keywords as those require an extra switch for those using it (e.g. `!` instead of `not`).
    - Solution: Include `<ciso646>` when using them or remove them completely.

Apparently that's all needed to get it working.

**Comment by Naav** [comment]
Regarding the `noexcept` fix for VS2013, explicitly defaulted constructors marked as `JSONPP_NOEXCEPT` will fail to compile. The solution is to have `JSONPP_NOEXCEPT` not expand to anything.

For example:

    format_options() JSONPP_NOEXCEPT = default;

Expands as:

    format_options() throw() = default;

Which fails to compile:

> error C2610: 'json::format_options::format_options(void) throw()' : is not a special member function which can be defaulted exception specification is not allowed
