### ISSUE TITLE
to_json mechanism easily breakable by implicit constructors

### ISSUE THREAD

**Issue by ThePhD** [Rapptz/jsonpp#15]
Out of the box types supported by the `dump` mechanism can cause overload resolution issues if other types that are implicitly constructible/convertible from the out of the box types are thrown into the `to_json` overload pool.

Consider the following code snippet:

```
struct jsonpp_breaker {
    jsonpp_breaker( nullptr_t ) {

    }
};

json::value to_json( jsonpp_breaker breaker ) {
    return json::value(1);
}

int main( int argc, const char* const argv[] ) {

    std::string s = json::dump_string( nullptr );

}
```

In Visual Studio 2015 (RC), this makes the internal call to `json::dump` fail due to ambiguous overloads. Upon inspection of the internals, it seems like the `Enable/DisableIf`s are too lenient when it comes to evaluating whether `to_json` is acceptable: things that collide with the core serialized types (like `nullptr` constructors and friends) will trigger ambigious overload errors.

One implementation idea is to use a more sophisticated overloading mechanism or use a templated enable-if-friendly `struct dumper<T, ...>` to capture appropriate types when considering which `dump` function to use (it's default case should use the `has_to_json<T>` enable_if and provide a clean static_assert when that fails, and otherwise call whatever `to_json` is available).

**Comment by Rapptz** [comment]
I can't reproduce this in GCC so as far as I can tell this might just be a Visual Studio issue.

The `EnableIf` is done with the following: `EnableIf<has_to_json<T>, Not<Or<is_object<T>, is_string<T>, is_array<T>>>>`.

Chances are I can just append `is_null<T>` to that list and hope it fixes it. If push comes to shove I can implement a more complicated way of doing overload resolution but I hope I don't have to resort to that.

**Comment by ThePhD** [comment]
That fixes one case, but the same happens for `double` args and the like.
In order to get it to build in VS 2015 RC, I had to do...

`EnableIf<has_to_json<T>, Not<Or<is_object<T>, is_string<T>, is_array<T>, is_null<T>, is_bool<T>, is_number<T>>>> = 0`

... Gnarly, but it works!
