### ISSUE TITLE
VS2013 does not support defaulting constructors with exception specifiers

### ISSUE THREAD

**Issue by naav** [Rapptz/jsonpp#17]
Regarding the `noexcept` fix for VS2013, explicitly defaulted constructors marked as `JSONPP_NOEXCEPT` will fail to compile.

For example:

```
format_options() JSONPP_NOEXCEPT = default;
```

Expands as:

```
format_options() throw() = default;
```

Which fails to compile:

> error C2610: 'json::format_options::format_options(void) throw()' : is not a special member function which can be defaulted exception specification is not allowed

**Comment by Rapptz** [comment]
This has been fixed already. See [here](https://github.com/Rapptz/jsonpp/blob/master/jsonpp/dump.hpp#L44). 2 weeks ago actually: d8eadc4dbe89bc2d59f1728b52f72ceb5be6af32

**Comment by naav** [comment]
How did I not see that.
