### ISSUE TITLE
Static assertions for as/is

### ISSUE THREAD

**Issue by DeadMG** [Rapptz/jsonpp#20]
I've noticed that when calling as or is with a type that they do not support, you get a runtime exception, even though you provide distinct overloads for this condition that just throw. It would be nice if this was replaced with a static_assert.

**Comment by Rapptz** [comment]
Originally I made it an exception because I didn't want compile time errors from hampering the generic programming case. I'm still not sure I want to do a `static_assert` there.

**Comment by DeadMG** [comment]
Not static_asserting hampers the generic programming case, because you're not letting the developer know that they got it wrong.

**Comment by Rapptz** [comment]
Throwing an exception is signalling that they got it wrong.

**Comment by Rapptz** [comment]
Fixed in https://github.com/Rapptz/jsonpp/commit/22336bc411b2904d1fb34ca8950ac207da354be3.
