### ISSUE TITLE
to_string does not properly dump real JSON.

### ISSUE THREAD

**Issue by Rapptz** [Rapptz/jsonpp#8]
Since it doesn't dump real JSON, it's probably not a good way to dump JSON. So it should probably be removed or renamed for a better API.

The reason it doesn't dump real JSON is because when dumping strings, it ignores the `\uxxxx` literals and even the escape sequences which makes it wrong.

It might be worth looking into how Python does JSON dumping. This allows it to be relevant to issue #5.

**Comment by ThePhD** [comment]
I don't know what you mean by "it ignores the \uxxxx" literaals. The actual `"\\u0041"` literal is changed?

**Comment by Rapptz** [comment]
`to_string` doesn't know about escape sequences at all. So `std::string x("\"\u0041\"")` would not turn into that in `to_string` with json. It'd turn into `""<char at 0x41>""` instead of `"\"\u0041\""`.

**Comment by Rapptz** [comment]
Basically fixed in 10f922c63c796c9d4422004d947cc3a0606f2278.
